### ISSUE TITLE
Understanding correlation when heritability is low

### ISSUE THREAD

**Issue by gpwhiz** [brielin/Popcorn#10]
Hi,
Thank you for the software.
We have computed LD from our population (not 1KG) which is admixed and another is EUR. The heritability estimate is low (0.001) for our admixed population but the correlation between two pops is high and p is 0.
If you can provide some guidance to interpret this result that would be great.

**Comment by brielin** [comment]
Hi gpwhiz,

When the heritability is low, the genetic correlation is essentially meaningless. The genetic correlation is only a meaningful quantity when the trait is highly polygenic and has significantly non-zero heritability. Moreover, when the heritability is low the estimate of the genetic correlation is biased. We discuss this in our follow up paper here: https://onlinelibrary.wiley.com/doi/10.1002/gepi.22173

Also as detailed in the original paper, Popcorn is not tested in admixed populations. The model is not the same when there is long-range LD induced by admixture and we make no attempt to account for this. I do not suggest that you use this method with admixed populations.

Thank you,
Brielin
