### ISSUE TITLE
Error when setting scores. Block width may exceed number of SNPs being stored Try increasing --SNPs_to_store

### ISSUE THREAD

**Issue by marielohcs** [brielin/Popcorn#12]
Hi popcorn team!
I've been running the code by chromosome for the compute scores part with no error, except chromosome 6 which now gives me the error "Error when setting scores. Block width may exceed number of SNPs being stored Try increasing --SNPs_to_store"

Could you possibly elaborate on what will be the way to select the 'optimum' number to set for "--SNPs_to_store"?

Many thanks!
Marie

**Comment by brielin** [comment]
The program doesn't read the entire genotype array into memory, instead it reads a certain number
in at a time. If the LD extends beyond the SNPs stored in memory, it generates this error.

It's not surprising that you would see this on Chr6 where the MHC region has very wide LD. Generally people remove this region for analysis.

There isn't really an optimum number. You can make it very large and the program will just take longer to run while producing the same output. The optimum is the smallest number that you can run without getting this error.
