### ISSUE TITLE
Inconsistent test results

### ISSUE THREAD

**Issue by FEIFEI502** [brielin/Popcorn#16]
Dear Popcorn group,

Thanks for the fantastic software. But when I test the data provided in the test file, the pg is 0.480(se 0.166) whereas 0.302(se 0.053) in your README file. Since I used the version 1.0, is it any update about the method?

Thanks in advance,
Fei-Fei

**Comment by harmjanwestra** [comment]
I'm getting the same values. Also I'm getting the following runtime warnings, which may be causing this issue?

[..]/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
[..]/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
[..]/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1738: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0

**Comment by brielin** [comment]
Hi, sorry I missed this the first time. You will get one value with `--use_mle` and the other without it. I probably forgot to change the readme when I changed the default. Let me know if this doesn't work. The warnings should be fine although I should update the code at some point to get rid of them.
