### ISSUE TITLE
ValueError: Input must be 1- or 2-d.

### ISSUE THREAD

**Issue by zhangchuyi** [brielin/Popcorn#18]
Dear Popcorn group,

Thanks for the fantastic software. I haved struggled in some problems for several days. I would appreciate it if you could give me any advice.

I  tried command like this: 
           `python __main__.py fit -v 1 --cfile ~/path/to/EUR_EAS_all_gen_imp.cscore --sfile1 ~/path/to/xx_eas_popcorn.txt --sfile2 ~/path/to/xx_eur_popcorn.txt correlation.txt`
Then I got following error :
> Initial estimate:
>          Val (obs)  SE
>   h1^2   0.660572 NaN
>   h2^2   0.094676 NaN
>   pg     0.176789 NaN
>   Performing jackknife estimation of the standard error using [(0, 10909), (10909, 21819), (21819, 32728), (32728, 43638), (43638, 54547), (54547, 65457), (65457, 76367), (76367, 87276), (87276,  98186), (98186, 109095), (109095, 120005),......,(2171009, 2181919)] blocks of size 10909 .
> ...
>  File "/home/lilab/zhangchuyi/anaconda3/envs/popcorn/lib/python3.8/site-packages/numpy/lib/twodim_base.py", line 283, in diag
>     raise ValueError("Input must be 1- or 2-d.")
>  ValueError: Input must be 1- or 2-d.

I have no idea what the error input is because my programming skills are to poor to understand most part of your python files.

Thanks in advance,
Chuyi Zhang

**Comment by brielin** [comment]
Unfortunately I have not been able to port this to Python 3 so only 2.7 is supported.
