### ISSUE TITLE
install POPCORN in Windows 7 

### ISSUE THREAD

**Issue by zhangchuyi** [brielin/Popcorn#19]
Dear Popcorn group,

Thanks for the fantastic software. I haved struggled in some problems for several days. I would appreciate it if you could give me any advice.

Someone else told me that she installed POPCORN under Windows 7 system and could run successfully, but when i tried this way, things went wrong again T-T.

>  WARNING: The wheel package is not available.
>  warning: no previously-included files found matching 'bottleneck\src\reduce.c'
>  warning: no previously-included files found matching 'bottleneck\src\move.c'
>  warning: no previously-included files found matching 'bottleneck\src\nonreduce.c'
>  warning: no previously-included files found matching 'bottleneck\src\nonreduce_axis.c'
>  warning: no previously-included files found matching 'bottleneck\src\bn_config.h'
>  warning: no previously-included files matching '*' found under directory 'doc\build'
>  warning: no previously-included files matching '__pycache__' found anywhere in distribution
>  warning: no previously-included files matching '*.pyc' found anywhere in distribution
>  warning: no previously-included files matching '*~' found anywhere in distribution
>  UPDATING build\lib.win-amd64-3.8\bottleneck/_version.py
>  set build\lib.win-amd64-3.8\bottleneck/_version.py to '1.3.2'
>  error: [WinError 5] 拒绝访问。: 
> 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\easy_install-ie8fos16\\Bottleneck-1.3.2\\.eggs\\numpy-1.19.5-py3.8-win-  
> amd64.egg\\numpy\\.libs\\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll'

I have tried to google these problems, however I did't find any practical solving methods. I would REALLY appreciate it if you could give me any advice.

**Comment by brielin** [comment]
Communicated elsewhere, Windows 7 is not officially supported so you're on your own there. Good luck!
