### ISSUE TITLE
Seeking help: can't replicate "Test files" results

### ISSUE THREAD

**Issue by Penguin0007** [brielin/Popcorn#27]
I'm trying to replicate the "Test files" section. Here are the commands I used:
(First to install and then run the "Test files" section)
git clone https://github.com/brielin/Popcorn.git
cd Popcorn
conda create -n popcorn python=2.7
source activate popcorn
pip install numpy==1.14.2
pip install scipy==1.0.1
pip install pandas==0.22.0
pip install pysnptools==0.3.9
pip install bottleneck==1.0.0
pip install statsmodels==0.8.0
python popcorn/__main__.py compute -v 2 --bfile1 test/EUR_ref --bfile2 test/EAS_ref --gen_effect test/EUR_EAS_test_ge.cscore
python popcorn/__main__.py fit -v 1 --cfile test/EUR_EAS_test_ge.cscore --gen_effect --sfile1 test/EUR_test.txt --sfile2 test/EAS_test.txt test/EAS_EUR_test_ge_result.txt

For the "compute" step, there's warning: FutureWarning: Conversion of the second argument of issubdtype from `str` to `str` is deprecated. In future, it will be treated as `np.string_ == np.dtype(str).type`.
  assert np.issubdtype(self._row.dtype, str) and len(self._row.shape)==2 and self._row.shape[1]==2, "iid should be dtype str, have two dimensions, and the second dimension should be size 2"
  assert np.issubdtype(self._col.dtype, str) and len(self._col.shape)==1, "sid should be of dtype of str and one dimensional"

For the "fit" step, there's warning: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0

And the output from "fit" is different from the "Test files" section: 
Initial estimate:
       Val (obs)  SE
h1^2   0.189627 NaN
h2^2   0.070971 NaN
pg     0.480240 NaN
Performing jackknife estimation of the standard error using 200 blocks of size 219 .
Jackknife iter: 200 
      Val (obs)        SE         Z         P (Z)
h1^2   0.189627  0.022386  8.470659  0.000000e+00
h2^2   0.070971  0.008623  8.230804  2.220446e-16
pge    0.480240  0.165895  3.133074  1.729856e-03

What command should I use to replicate the result in "Test files" section instead? Thank you!

**Comment by Penguin0007** [comment]
There's still slight difference and warning in "fit" step after adding --use_mle:

RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0
Initial estimate:
       Val (obs)  SE
h1^2   0.172133 NaN
h2^2   0.086708 NaN
pg     0.302367 NaN
Performing jackknife estimation of the standard error using 200 blocks of size 219 .
/depot/bingxin/data/LDSC&EHR/LDSC/Popcorn/popcorn/fit.py:180: RuntimeWarning: invalid value encountered in log
  - 0.5*np.sum(W*(Z**2/S))
Jackknife iter: 200 
      Val (obs)        SE          Z  P (Z)
h1^2   0.172133  0.012871  13.373696    0.0
h2^2   0.086708  0.008554  10.136059    0.0
pge    0.302367  0.053020  13.158032    0.0

**Comment by TaoShiyue** [comment]
Hi! I faced the same question. How did you solve it?

**Comment by Penguin0007** [comment]
> Hi! I faced the same question. How did you solve it?

The author said this minor difference is OK... So I guess it's not big issue.

**Comment by TaoShiyue** [comment]
> > Hi! I faced the same question. How did you solve it?
> 
> The author said this minor difference is OK... So I guess it's not big issue.

Okay, thank you!
