### ISSUE TITLE
input files

### ISSUE THREAD

**Issue by zammyfh** [brielin/Popcorn#3]
Hiya, 

I really enjoyed reading your 'Transethnic Genetic-Correlation Estimates from Summary Statistics' paper and am keen to employ the method you developed in my own work. I have GWAS data on both EUR and EAS, which intersect at 5 million SNPs with maf >5%. Would you advice me to include all 5 million SNPs in the bfiles used to compute the scores, or should I use a smaller sample of the SNPs? I have access to the individual level data so was wondering whether you would recommend creating the bfiles from the data I am working on, or from 1000 genomes/hapmap. Additionally how many individuals would you suggest to be included in the bfiles?

Sorry to post all these questions as an issue, as you are no longer at Berkeley I wasn't sure if you would still be using the email attached to your GitHub account.

Thanks!
Zammy

**Comment by brielin** [comment]
Hey Zammy,

My Berkeley email still works, but thanks for pointing it out - I changed it to my gmail account.

As for your question, that is probably best discussed over email. Go ahead and shoot me an email to my gmail account and we can discuss. Access to the individual level data changes a lot about the best practices.

Cheers,
Brielin
