### ISSUE TITLE
'beta' & 'SE' works but 'OR' & 'p-value' does not, how to preprocesss summary statistics (Neff)

### ISSUE THREAD

**Issue by char4816** [brielin/Popcorn#7]
Thank you for making this software.  I have been organizing summary stats to run through popcorn and have noticed that when I use 'beta' & 'SE', the _fit_ returns some results (yay!).  However, when I try to use the 'OR' & 'p-value' options as described in your documentation (which are the options I would prefer to use, given my summary stats files), the h2 outputs are always zero.  For now I can use the 'beta' & 'SE' option, but I hope I can help you improve upon this issue so the software is even more adaptable to various sum stat formats.

A make-shift solution I found is using the equations from your odds_to_beta() function in sumstats.py to preprocess my files in R
suppose you have a sumstat file with a header that is limited with the following following columns
_rs     ref     alt     chr     pos     or     pval_
`sumstats <- read.table("orig_sumstats.txt", header=T, stringsAsFactor=F)`
`sumstats$N <- 4/(1/nr.cases+1/nr.controls)`
`sumstats$beta <- log(sumstats$or)`
`sumstats$Z <- sign(sumstats$beta)*qnorm(1 - sumstats$pval/2)`
`sumstats$SE <- sumstats$beta/sumstats$Z`
`sumstats <- sumstats[,c("rs", "ref", "alt", "N", "beta", "SE")]`
`colnames(asthmaAdult) <- c("SNP", "a1", "a2", "N", "beta", "SE")`
`write.table(sumstats,"sumstats.txt", sep = "\t", col.names=T, row.names=F, quote=F)`

Since many summary stats files do not have an "N" column, it can be difficult for users to distinguish the correct N to use. It doesn't always make sense to just sum nr.cases+nr.controls. Many people use the above equation for N when controls are in imbalance, for example: 
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5726434/
- https://www.biorxiv.org/content/biorxiv/early/2019/07/22/133132.full.pdf
- https://github.com/bulik/ldsc/issues/95

The math behind the Neff calculation stems from the variance inflation factor (https://journals.sagepub.com/doi/pdf/10.1177/0163278703255230) between balanced and unbalanced studies. If you agree with me, you may want to advise users in your README to use this formula for N when it isn't provided by the summary stats and nr.cases != nr.controls 

I hope this helps!

Thanks,
Chris

**Comment by char4816** [comment]
I thought my above solution would work, however I am still getting 0 results for the output after converting pvalue & or to beta & SE... I think this suggests that there may be an error in the odds_to_beta() function.

**Comment by char4816** [comment]
I think your documentation has a typo and that you mean to say: eg. signed wrt A1 as effect in pop1 and **_A1_** (NOT A2) as effect in pop2

**Comment by brielin** [comment]
Thanks Chris, I'll look into this today and let you know what I come up with.

**Comment by brielin** [comment]
Quick comment: N_cases + N_controls is the value you want for N, not Neff. As noted in the link to the LDSC issue you posted, the conversion to the liability scale handles the imbalance between cases and controls.

**Comment by char4816** [comment]
Thank you for your help and taking the time to collaborate on this.  In the ldsc issue they describe how it is roughly equivalent to 1) use N=Cases+Controls and the appropriate --samp-prev or to 2) use Neff = 4/(1/nr.cases+1/nr.controls) with --samp-prev 0.5

I am interpreting that nr.cases+nr.controls is correct as long as the user specifies prevalence values for the disease so that conversion to liability scale is accurate.  Am I correct in this interpretation of the _fit_ variables?
--K1 = "population prevelance of binary phenotype 1" (prevalence of phen1 in literature)
--P1 = "study prevelance of binary phenotype 1" (nr.cases/(nr.cases+nr.controls) for sfile1)
--K2 = "population prevelance of binary phenotype 2" (prevalence of phen2 in literature)
--P2 = "study prevelance of binary phenotype 2" (nr.cases/(nr.cases+nr.controls) for sfile2)

**Comment by brielin** [comment]
Yes, exactly. I'm updating the readme in the next push to clarify. Still looking into the OR/beta issue.

**Comment by char4816** [comment]
Thank you! I am realizing I should have said 
--P1 = "study prevelance of binary phenotype 1" (nr.cases/(nr.controls + nr.controls)for sfile1)
--P2 = "study prevelance of binary phenotype 1" (nr.cases/(nr.controls + nr.controls)for sfile2)
that way --P1 = 0.5 when nr.cases and nr.controls are balanced
I'll edit the above comment to correct this

**Comment by brielin** [comment]
I'm struggling to find any issue in the odds ratio conversion. When you say you get the beta and SE version to work, is this the same trait? Always getting 0 tells me it could be a few things:

- Something is going wrong in the conversion step and all of the Z-scores/betas are getting set to 0 or something weird. When you run the R code you have, is this happening? It doesn't seem to happen for me on the python side.
- The heritability is actually very low and the MLE is 0. I just pushed an update which changes the default behavior to use regression instead, but on the older version you can use "--use_regression" to use a simpler model instead of MLE.

Otherwise, if you don't mind sharing your sumstats file (you can send me an email if you like) I can try to debug more directly.

**Comment by char4816** [comment]
I have a good example of summary stats files and will follow up via email in a few minutes

**Comment by brielin** [comment]
Fixed in the latest update. Conversion was resulting in NaNs/infs that needed to be filtered.
