### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by joomango** [brielin/Popcorn#8]
It seems like the codes are basically written in Python 2.7 but the environment requires Python >3.5 to run the code. 

They are not compromising but crashing each other. I keep getting the **NameError: name 'xrange' is not defined** . Xrange() is no longer working in python3 as you might already know. For this reason, if I try to run the code again in python2.7, it keeps aborted for not fulfilling the system requirement. What should I do?

Please specify the right python version/environment to run the code correctly. - I really want to resolve this issue as soon as possible. Thanks a lot,

**Comment by brielin** [comment]
I replied to your email. This was developed in and should be run in Python 2.7. I'm not sure what system requirement issue you're running into.
